"""Add email verification token columns

Revision ID: 6dd47598814e
Revises: 8f2d6c1a9b30
Create Date: 2026-07-06 21:53:00.781388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd47598814e'
down_revision = '8f2d6c1a9b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_reference'))
        batch_op.create_index(batch_op.f('ix_payments_provider_reference'), ['provider_reference'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token_expires')
        batch_op.drop_column('email_verification_token')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_reference'))
        batch_op.create_index(batch_op.f('ix_payments_provider_reference'), ['provider_reference'], unique=False)

    # ### end Alembic commands ###
